### ISSUE TITLE
Add prettier , husky and lint staged in the project

### ISSUE THREAD

**Issue by aloksingh3112** [orcasound/orcamap#16]
Currently the project includes just a eslint file , I think we should include a prettier file and pre-commit hooks using husky and lint-staged to improve the developer experience.

**Comment by aloksingh3112** [comment]
@ivanoats @scottveirs

**Comment by ivanoats** [comment]
Definitely good idea.

**Comment by ivanoats** [comment]
FYI, Looks like eslint is already running prettier.

**Comment by ivanoats** [comment]
Work done on https://github.com/orcasound/orcamap-react repo: 

https://github.com/orcasound/orcamap-react/commit/8cd1852596529f31bac8277c564a0042212d3e8b
